GET http://localhost:3030/product

###

POST http://localhost:3030/product
Content-Type: application/json

{
  "brand": "nokia",
  "model": "nokia 125",
  "cost": 400
}

###

GET http://localhost:3030/product/63061fbb7769bd14adf52eda


###

PUT http://localhost:3030/product/63061fbb7769bd14adf52eda
Content-Type: application/json

{
  "brand": "xiaomi",
  "model": "note 10"
}

###

DELETE http://localhost:3030/product/6306ee065128aed0e977c5ff