GET http://localhost:3030/product

###

POST http://localhost:3030/product
Content-Type: application/json

{
  "brand": "nokia",
  "model": "test",
  "cost": 400
}

###

GET http://localhost:3030/product/63061fbb7769bd14adf52eda


###

PUT http://localhost:3030/product/63061fbb7769bd14adf52eda
Content-Type: application/json

{
  "brand": "xiaomi"
}

###

DELETE http://localhost:3030/product/6306213c0ab54344ec2a8be9