GET http://localhost:3030/product

###

POST http://localhost:3030/product
Content-Type: application/json

{
  "model": "redmi note 5 pro",
  "processor": "snapdragon 636",
  "cost": 400
}

###

GET http://localhost:3030/product/6307010fe27f77d759618615


###

PUT http://localhost:3030/product/6307010fe27f77d759618615
Content-Type: application/json

{
  "model": "redmi 8a",
  "processor": "mediatek"
}

###

DELETE http://localhost:3030/product/6307010fe27f77d759618615